### ISSUE TITLE
Few question for contributions

### ISSUE THREAD

**Issue by MatthD** [kornelski/xml-rs#16]
Hello !!

First thanks for your hard job on the xml-rs library you work on.

On my side I am the maintainer of [node-Libxml](https://www.npmjs.com/package/node-libxml), I wrote it in native node module (C binding of libxml compiled) .
And it’s only doing wellformed check, DTD/XSD validation and data recuperation via xPath.

I would be happy to move to Rust with neon-bindings.

1. I was playing with you library, so my first question is, does xml-rs implement all the 6 points of a xml-wellformed check or do I have to use your lib as a stream parser and do it on my side ?
2. Seconde question is that it appears the parser exit with a panic if it’s not wellformed on the first error (for example when an element is not closed before another was opened); do you think there is a way to encapsulate your event on my side so that your parser can continue the job after an error and we can have all the wellformed errors instead of just the first one with an exit ? I saw at `reader.rs` line [142](https://github.com/kornelski/xml-rs/blob/main/src/reader.rs#L142) that we stop with an error and try to just remove this part but really not sure about that ;) 
3. Third question, do you think for DTD/XPATH implement we should work on a branch/for of your repo or we should work on another repository that use your lib and extends it ? What do you prefer

Regards😉

Matthias

**Comment by kornelski** [comment]
The library checks as much well-formedness as it can. I'm not sure which 6 you mean, because the XML spec lists way more criteria. The weakest point in well-formedness checks is probably in handling of edge cases of nested entities, especially pe entities. 

As much as possible, this library returns errors using `Result`. It might throw a panic if due to a bug in the code. So you shouldn't need to handle panics in normal operation, but make sure nothing catastrophic happens if it panics (e.g. use catch_unwind to avoid unwinding across FFI boundary).

I'm not interested in XPath, so this should be a separate library. 

I am interested in having proper DTD support. It could be via a separate library that can be plugged into xml-rs. If you implement it, make sure to give library users precise control over reading of files and URLs, since they're a security nightmare (if you just load anything XML asks for, it will be used for exfiltration of local data, or DoS of other hosts).
Also if you're planning to write a DTD parser, don't copy xml-rs's parsing architecture :) The bottom-up event-based parser is hard to optimize, and a top-down parser could be much faster.

**Comment by MatthD** [comment]
Thanks !

I did a mistake talking about the panic, in fact as I understand the code it stop the parser when encountering an error, so that  it could not get all the possible errors.

For eg in an XML like this one it will say that `</to>` is done instead of `</my>`and will not send **EndElement** event for `</xpath>`, is there a way to continue to parse even if there is an error ?

```xml
<xpath>
    <to>
        <my>
            <infos>trezaq</infos>
    </to>
</xpath>
```

**Comment by kornelski** [comment]
xml-rs treats this error according to the XML spec: it's a fatal error, which must be reported to the application, and normal parsing must not continue.

If you need to parse files that aren't XML, see: https://lib.rs/crates/xml5ever
